spring:
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    username: root
    password: x.z.w.91
  # redis
  redis:
    database: 0
    host: 101.43.171.193
    password: asd123
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        max-wait: -1
        min-idle: 0
    port: 6379
    timeout: 1800000
  cloud:
    nacos:
      discovery:
        namespace: guli-xueyuan
        server-addr: 8.134.162.31:8848
