server:
  port: 9001
spring:
  application:
    name: service-gateway
  cloud:
    nacos:
      discovery:
        namespace: guli-xueyuan
        server-addr: 8.134.162.31:8848
        group: PROD_GROUP
    gateway:
      #      跨域配置文件
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true #开启后,新增一种访问方式:localhost:9527/服务名/资源路径 原访问方式为localhost:9527/资源路径 #是否使用service-id 的小写， 默认是大写。
          lower-case-service-id: true #是否启动服务名小写
      routes:
        - id: service-edu
          predicates: Path=/eduservice/**
          uri: lb://service-edu
          swagger-name: "课程教师接口"
        - id: service-ucenter
          predicates: Path=/educenter/**
          uri: lb://service-ucenter
          swagger-name: "用户中心"

        - id: service-cms
          predicates: Path=/educms/**
          uri: lb://service-cms
          swagger-name: "首页轮播图"

        - id: service-msm
          predicates: Path=/edumsm/**
          uri: lb://service-msm
        - id: service-order
          predicates: Path=/orderservice/**
          uri: lb://service-order

        - id: service-oss
          predicates: Path=/eduoss/**
          swagger-name: "文件上传"
          uri: lb://service-oss

        - id: service-statistics
          predicates: Path=/staservice/**
          swagger-name: "统计数据生成"
          uri: lb://service-statistics

        - id: service-vod
          predicates: Path=/eduvod/**
          swagger-name: "视频点播"
          uri: lb://service-vod

