server:
  port: 9002
spring:
  application:
    name: service-doc
knife4j:
  enableAggregation: true
  cloud:
    enable: true
    serviceUrl: http://8.134.162.31:8848/nacos/
    routes:
      - name: 课程服务
        uri: localhost:8001
        location: /v2/api-docs
      - name: 轮播图服务
        uri: localhost:8004
        location: /v2/api-docs
      - name: 订单服务
        uri: localhost:8004
        location: /v2/api-docs
