spring:
  rabbitmq:
    host: beta.ynu.icu
    port: 5672
    virtual-host: /
    publisher-confirm-type: correlated #消息从发送端到达交换机的确认
    publisher-returns: true #消息从交换机抵达队列的确认
    template:
      mandatory: true #以异步发送优先回调returnConfirm 这个配不配无所谓
    listener:
      simple:
        acknowledge-mode: manual #关闭自动应答,消息处理完成后需要手动应答
  jackson:
    modules:
      - com.fasterxml.jackson.datatype.jsr310.JavaTimeModule
    serialization:
      write-dates-as-timestamps: false
  main:
    allow-circular-references: true
# 限速器:限制一段时间内的访问数
resilience4j.ratelimiter:
  instances:
    default:
      limitRefreshPeriod: 1s #周期时长
      limitForPeriod: 100 #每个周期最多多少请求
      timeoutDuration: 3s #没拿到令牌,最多等多久